# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dl_abi.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64l_abi.proto\"6\n\x07\x41\x42Image\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\"]\n\x0ePredictRequest\x12\x12\n\nmodel_path\x18\x01 \x01(\t\x12\x13\n\x0b\x63onfig_path\x18\x02 \x01(\t\x12\x10\n\x08img_path\x18\x03 \x01(\t\x12\x10\n\x08redun_id\x18\x04 \x01(\t\"\x8f\x01\n\x0fPredictRespense\x12\x10\n\x08redun_id\x18\x01 \x01(\t\x12\x10\n\x08is_error\x18\x02 \x01(\x08\x12\x15\n\rerror_message\x18\x03 \x01(\t\x12\x13\n\x0bres_g_ratio\x18\x04 \x01(\x02\x12\x13\n\x0bres_y_ratio\x18\x05 \x01(\x02\x12\x17\n\x05image\x18\x06 \x01(\x0b\x32\x08.ABImage2;\n\tPredictor\x12.\n\x07predict\x12\x0f.PredictRequest\x1a\x10.PredictRespense\"\x00\x62\x06proto3')



_ABIMAGE = DESCRIPTOR.message_types_by_name['ABImage']
_PREDICTREQUEST = DESCRIPTOR.message_types_by_name['PredictRequest']
_PREDICTRESPENSE = DESCRIPTOR.message_types_by_name['PredictRespense']
ABImage = _reflection.GeneratedProtocolMessageType('ABImage', (_message.Message,), {
  'DESCRIPTOR' : _ABIMAGE,
  '__module__' : 'dl_abi_pb2'
  # @@protoc_insertion_point(class_scope:ABImage)
  })
_sym_db.RegisterMessage(ABImage)

PredictRequest = _reflection.GeneratedProtocolMessageType('PredictRequest', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTREQUEST,
  '__module__' : 'dl_abi_pb2'
  # @@protoc_insertion_point(class_scope:PredictRequest)
  })
_sym_db.RegisterMessage(PredictRequest)

PredictRespense = _reflection.GeneratedProtocolMessageType('PredictRespense', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTRESPENSE,
  '__module__' : 'dl_abi_pb2'
  # @@protoc_insertion_point(class_scope:PredictRespense)
  })
_sym_db.RegisterMessage(PredictRespense)

_PREDICTOR = DESCRIPTOR.services_by_name['Predictor']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ABIMAGE._serialized_start=16
  _ABIMAGE._serialized_end=70
  _PREDICTREQUEST._serialized_start=72
  _PREDICTREQUEST._serialized_end=165
  _PREDICTRESPENSE._serialized_start=168
  _PREDICTRESPENSE._serialized_end=311
  _PREDICTOR._serialized_start=313
  _PREDICTOR._serialized_end=372
# @@protoc_insertion_point(module_scope)
